#!/bin/bash

remote="$1"
url="$2"

red=$(tput setaf 1)
reset=$(tput sgr0)

while read local_ref local_sha remote_ref remote_sha
do
    if git show --pretty="format:%ce" $local_sha | grep "@example.com$"; then
        echo >&2 "${red}Bad committer on commit $(echo "$local_sha" | cut -c 1-8). Fix it before you push${reset}"
        exit 1
    fi
done

exit 0
