#!/usr/bin/env bash

current_branch=`git rev-parse --abbrev-ref HEAD`

if [[ ! ${current_branch} == "master" ]]; then
	exit 0
fi

egrep -ir --include '*.java'  '//\W*todo' src > /dev/null
if [ $? -ne 1 ]; then
  echo "Found 'todo' comments. Please remove these (doing them or adding tasks/chores as appropriate) before pushing."
  exit 1
else
  exit 0
fi
