#!/usr/bin/env bash

java -jar /usr/local/bin/google-java-format*.jar --replace $(git diff --name-only --cached)
git add $(git diff --name-only --cached)

git diff --name-only --cached --relative | grep '\.kts\?$' | xargs ktlint --relative .
if [ $? -ne 0 ]; then exit 1; fi

exit 0
