#!/bin/bash

IFS=$'\n'
FOCUSED_TESTS_REGEX="(FDescribe|FContext|FIt|FWhen)"

files_with_focused_tests=()
changed_files="$(git diff --name-only --diff-filter=AM --cached | grep -E -v '^vendor/' | grep -E '.*\.go$')"
if [ -n "$changed_files" ]; then
    for changed_file in $changed_files; do
        if git diff -U0 --cached -- "$changed_file" | grep -q -E "^\\+.*$FOCUSED_TESTS_REGEX"; then
            files_with_focused_tests+=("$changed_file")
        fi
    done

    if [ -n "$files_with_focused_tests" ]; then
        echo "Focused tests found in the following added or modified files:"
        for file in "${files_with_focused_tests[@]}"; do
            echo "   - $file"
        done
        echo "Please remove the focused tests from these files"
        echo "To commit anyway, add '-n' flag to 'git ci'"
        exit 1
    fi
fi

exit 0
