#!/usr/bin/env bash

output=$( git diff --cached | cred-alert scan --diff)
status="$?"
if [ "${status}" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the commit! Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"
fi
exit "${status}"
