#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
red="\033[31m"
default="\033[0;1m"

if ! command -v "cred-alert-cli" >/dev/null 2>&1; then
  echo -e "${bold}Uh oh! It looks like you don't have ${red}cred-alert${default} installed!${normal}"
  echo
  echo "You have a hook installed [1] that uses cred-alert to scan for"
  echo "accidentally committed credentials. You can install cred-alert by"
  echo "following these steps:"
  echo

  if [ "$(uname)" == "Darwin" ]; then
    echo "    curl -O https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_darwin"
    echo "    install cred-alert-cli_darwin /usr/local/bin/cred-alert-cli"
    echo "    rm cred-alert-cli_darwin"
  else
    echo "    curl -O https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_linux"
    echo "    install cred-alert-cli_linux /usr/local/bin/cred-alert-cli"
    echo "    rm cred-alert-cli_linux"
  fi

  echo
  echo "We won't interrupt this commit message (and so this commit won't be"
  echo "scanned!) but you should install this as soon as possible."
  echo
  echo "Thanks!"
  echo
  echo "[1]: ${0}"

  exit
fi

output=$( git diff --cached | cred-alert-cli scan --diff --show-suspected-credentials)
status="$?"
if [ "${status}" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the commit! Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"
fi
exit "${status}"
