#!/usr/bin/env bash

COMMIT_MSG_FILE=$1

if [[ -z "$PIVOTAL_TRACKER_TOKEN" || -z "$PIVOTAL_TRACKER_PROJECT_ID" ]]; then
  echo "WARNING: Can't prompt for Pivotal Tracker id without \$PIVOTAL_TRACKER_TOKEN "
  echo "or \$PIVOTAL_TRACKER_PROJECT_ID"
  echo "Please include this variable in your .envrc."
  exit 1
fi
if [[ -z "$(command -v jq)" ]]; then
  echo "WARNING: Can't prompt for Pivotal Tracker id without installing jq."
  echo "Please brew install jq."
  exit 1
fi
if [[ -z "$(command -v fzf)" ]]; then
  echo "WARNING: Can't prompt for Pivotal Tracker id without installing fzf."
  echo "Please brew install fzf."
  exit 1
fi

ISSUE_ID=$( \
  curl -sfG -X GET -H "X-TrackerToken: $PIVOTAL_TRACKER_TOKEN" \
    --data-urlencode "filter=state:started" \
    --data-urlencode fields=name https://www.pivotaltracker.com/services/v5/projects/$PIVOTAL_TRACKER_PROJECT_ID/stories \
  | jq -r 'map({id: .id|tostring, name: .name})|map(.id+": "+.name)|.[]' \
  | fzf --multi \
  | sed -E -e 's/^([[:digit:]]+):.+$/#\1/' \
  | tr '\n' ', ' \
  | sed -E -e 's/^(.*),$/[\1]/'
)
if [[ ! -z "$ISSUE_ID" ]]; then
  FILE="$COMMIT_MSG_FILE"
  cat $FILE > /tmp/filecontents
  printf "\n\n" > $FILE
  echo $ISSUE_ID >> $FILE
  cat /tmp/filecontents | tail -n +2 >> $FILE
  rm /tmp/filecontents
else
  echo "You didn't pick a Pivotal Tracker issue ಠ_ಠ"
  exit 0
fi
