#!/usr/bin/env bash

if ! command -v "cred-alert-cli" >/dev/null 2>&1; then
  exit
fi

if [ -f .git ] ; then
  ORIG_HEAD=$(sed 's/^gitdir: *//' .git)/ORIG_HEAD
else
  ORIG_HEAD=.git/ORIG_HEAD
fi

if [ ! -e "${ORIG_HEAD}" ] ; then
    echo "${ORIG_HEAD} isn't a valid file"
    exit 0
fi

output=$( git diff "$( cat "${ORIG_HEAD}" )..HEAD" | cred-alert-cli scan --diff --show-suspected-credentials)
status="$?"
if [ "${status}" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the merge! Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"
fi
exit "${status}"
