#!/usr/bin/env bash

if ! command -v "cred-alert-cli" >/dev/null 2>&1; then
  exit
fi

output=$( git diff $( cat .git/ORIG_HEAD )..HEAD | cred-alert-cli scan --diff --show-suspected-credentials)
status="$?"
if [ "${status}" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the merge! Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"
fi
exit "${status}"
