#!/usr/bin/env bash

if ! command -v "cred-alert-cli" >/dev/null 2>&1; then
  exit
fi

output=$(cred-alert-cli scan -f "${1}" --show-suspected-credentials)
status="$?"
if [ "$status" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the commit message!\n Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"

  printf "\n"
  printf "Your commit message:\n\n"
  printf "=====================================================================\n"
  sed '/# ------------------------ >8 ------------------------/Q' | sed '/# /Q' < "${1}"
  printf "=====================================================================\n"
fi
exit "$status"
