#!/usr/bin/env bash

output=$(cred-alert scan -f "${1}")
status="$?"
if [ "$status" -eq 3 ]; then
  printf "\n"
  printf "Found possible credentials in the commit message!\n Locations are listed below:\n"
  printf "\n"
  printf "%s" "$output"
  printf "\n"
fi
exit "$status"
